# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-17 10:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protest', '0002_auto_20160917_0830'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField()),
                ('agree_count', models.IntegerField()),
                ('type', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow_id', models.IntegerField()),
                ('type', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('support_count', models.IntegerField()),
                ('against_count', models.IntegerField()),
                ('neutral_count', models.IntegerField()),
                ('organizing_committee', models.CharField(max_length=100)),
                ('age_group', models.CharField(max_length=25)),
                ('dateTime', models.DateTimeField(auto_now_add=True)),
                ('incident', models.TextField()),
                ('closed', models.BooleanField(default=0)),
                ('picture', models.CharField(max_length=1000)),
                ('tag', models.CharField(max_length=100)),
                ('concerned_authority', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=1)),
                ('location', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=50)),
                ('about_yourself', models.TextField()),
                ('post_count', models.IntegerField()),
                ('registered_on', models.DateField(auto_now_add=True)),
                ('contact_no', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='profile_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protest.Profile'),
        ),
        migrations.AddField(
            model_name='follow',
            name='profile_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protest.Profile'),
        ),
        migrations.AddField(
            model_name='comment',
            name='post_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protest.Post'),
        ),
        migrations.AddField(
            model_name='comment',
            name='profile_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protest.Profile'),
        ),
        migrations.AddField(
            model_name='agree',
            name='comment_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protest.Comment'),
        ),
        migrations.AddField(
            model_name='agree',
            name='profile_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protest.Profile'),
        ),
    ]
